name: AddBinderBadge
on:
  pull_request_target:
    branches:
      - main
    types: [opened]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'

jobs:
  build-image-without-pushing:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Comment on PR with Binder link
      uses: actions/github-script@v3
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        CONTENT_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var BRANCH_NAME = process.env.BRANCH_NAME;
          var CONTENT_REPO = process.env.CONTENT_REPO;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${CONTENT_REPO}/${BRANCH_NAME}?urlpath=lab) :point_left: Launch a binder notebook on this branch`
          })
